# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://fizal.me
baseurl:
title: Fizal Sarif
author: Fizal Sarif
description: Personal blog and portfolio
avatar: profile.png
email: fizal.sarif@gmail.com
github: fizal619 # username
twitter: Fizal619
linkedin: fizalsarif
stackoverflow:    #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus:
google_analytics:

highlighter: rouge


